USERNAME = "yourkayoemail@domain.com"
PASSWORD = "Y0urP@s5w0rd"
TOKEN = "32j3k4j1klj23"
REFRESH_TOKEN = "23932o932j1klmj1kj"
TOKEN_EXPIRES_IN = 300

PROFILE_ID = "skajdkaj"
PROFILE_ROOT = True
PROFILE_NAME = "YourKayo"
PROFILE_FIRST_NAME = "Your"
PROFILE_LAST_NAME = "Kayo"
PROFILE_AVATAR_ID = 3
PROFILE_ONBOARDING_STATUS = "onboarded"
PROFILE_PH_NUM = "+61 999 999 999"
PROFILE_EMAIL = "yourkayoemail@domain.com"

EVENT_ID = "Test Profile"
EVENT_TITLE = "YourKayo"
EVENT_DESCRIPTION = "Test Description"
EVENT_SPORT = "Test Sport"
EVENT_SERIES_ID = 1
EVENT_CATEGORY_ID = 2

